apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-config
  namespace: bind9
data:
  named.conf: |
    //
    // named.conf
    //
    // Provided by Red Hat bind package to configure the ISC BIND named(8) DNS
    // server as a caching only nameserver (as a localhost DNS resolver only).
    //
    // See /usr/share/doc/bind*/sample/ for example named configuration files.
    //

    options {
      listen-on-v6 { any; };
      directory 	"/var/named";
      dump-file 	"/var/named/data/cache_dump.db";
      statistics-file "/var/named/data/named_stats.txt";
      memstatistics-file "/var/named/data/named_mem_stats.txt";
      /*
      - If you are building an AUTHORITATIVE DNS server, do NOT enable recursion.
      - If you are building a RECURSIVE (caching) DNS server, you need to enable
        recursion.
      - If your recursive DNS server has a public IP address, you MUST enable access
        control to limit queries to your legitimate users. Failing to do so will
        cause your server to become part of large scale DNS amplification
        attacks. Implementing BCP38 within your network would greatly
        reduce such attack surface
      */
      recursion yes;

      /* Path to ISC DLV key */
      bindkeys-file "/etc/bind/named.iscdlv.key";

      managed-keys-directory "/var/named/dynamic";

      pid-file "/run/named/named.pid";
      session-keyfile "/run/named/session.key";
      check-names master ignore;
      check-names slave ignore;
      allow-transfer {
        192.168.1.30;
        };
      also-notify {
        };
      notify yes;
      forward first;
      dnssec-validation auto;
    };

    logging {
        channel query_logging {
            file "/var/log/query.log";
            severity info;
            print-time yes;
        };
        category queries { query_logging; };
    };

    include "/etc/bind/rndc.key";

    controls {
        inet 127.0.0.1 port 953 allow { 127.0.0.1; } keys { rndc-key; };
    };


    acl internals {
        127.0.0.0/8;
        192.168.1.0/24;
        192.168.10.0/24;
        192.168.20.0/24;
        192.168.30.0/24;
        192.168.50.0/24;
        192.168.60.0/22;
        10.0.0.0/16;
        10.233.0.0/18;
        10.233.64.0/18;
        2604:2d80:6982:6700::/64;
    };

    view "internal" {
      match-clients {
          internals;   // ðŸ‘ˆ for testing, allow everyone
      };
        zone "." IN {
            type hint;
            file "named.ca";
        };
        zone "ghosthacker.com" {
            type master;
            file "/var/named/internals/db.ghosthacker.com";
      allow-update { 192.168.1.17; };
        };

        zone "vsphere65.local" {
            type master;
            file "/var/named/internals/db.vsphere65.local";
            allow-update { 192.168.1.17; };
            //update-policy { grant *.ghosthacker.com. self ghosthacker.com. A; };
        };

      include "/etc/bind/named.rfc1912.zones";
      include "/etc/bind/named.root.key";
      zone "ghosthacker.local" {
        type slave;
        masters {
          192.168.1.30;
          192.168.1.31;
          };
        file "/var/named/slaves/ghosthacker.local.internal.hosts";
        };
      zone "k8s.ghosthacker.com" {
        type master;
        file "/var/named/k8s.ghosthacker.com.internal.hosts";
        };
    };

    view "external" {
      match-clients {
        any;
        };
        zone "ghosthacker.com" {
            type master;
            file "/var/named/externals/db.ghosthacker.com";
            //allow-transfer { slaves; };
        };
        zone "ghosthacker.xyz" {
      type master;
      file "/var/named/externals/db.ghosthacker.xyz";
        };
    };

    trusted-keys {
      };
    server 192.168.1.168 {
      };

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iscdlvkey-config
  namespace: bind9
data:
  named.iscdlv.key: | 
    # The bind.keys file is used to override the built-in DNSSEC trust anchors
    # which are included as part of BIND 9.  As of the current release, the only
    # trust anchors it contains are those for the DNS root zone ("."), and for
    # the ISC DNSSEC Lookaside Validation zone ("dlv.isc.org").  Trust anchors
    # for any other zones MUST be configured elsewhere; if they are configured
    # here, they will not be recognized or used by named.
    #
    # The built-in trust anchors are provided for convenience of configuration.
    # They are not activated within named.conf unless specifically switched on.
    # To use the built-in root key, set "dnssec-validation auto;" in
    # named.conf options.  To use the built-in DLV key, set
    # "dnssec-lookaside auto;".  Without these options being set,
    # the keys in this file are ignored.
    #
    # This file is NOT expected to be user-configured.
    #
    # These keys are current as of Feburary 2017.  If any key fails to
    # initialize correctly, it may have expired.  In that event you should
    # replace this file with a current version.  The latest version of
    # bind.keys can always be obtained from ISC at https://www.isc.org/bind-keys.

    managed-keys {
            # ISC DLV: See https://www.isc.org/solutions/dlv for details.
            #
            # NOTE: The ISC DLV zone is being phased out as of February 2017;
            # the key will remain in place but the zone will be otherwise empty.
            # Configuring "dnssec-lookaside auto;" to activate this key is
            # harmless, but is no longer useful and is not recommended.
            dlv.isc.org. initial-key 257 3 5 "BEAAAAPHMu/5onzrEE7z1egmhg/WPO0+juoZrW3euWEn4MxDCE1+lLy2
                    brhQv5rN32RKtMzX6Mj70jdzeND4XknW58dnJNPCxn8+jAGl2FZLK8t+
                    1uq4W+nnA3qO2+DL+k6BD4mewMLbIYFwe0PG73Te9fZ2kJb56dhgMde5
                    ymX4BI/oQ+cAK50/xvJv00Frf8kw6ucMTwFlgPe+jnGxPPEmHAte/URk
                    Y62ZfkLoBAADLHQ9IrS2tryAe7mbBZVcOwIeU/Rw/mRx/vwwMCTgNboM
                    QKtUdvNXDrYJDSHZws3xiRXF1Rf+al9UmZfSav/4NWLKjHzpT59k/VSt
                    TDN0YUuWrBNh";

            # ROOT KEYS: See https://data.iana.org/root-anchors/root-anchors.xml
            # for current trust anchor information.
            #
            # These keys are activated by setting "dnssec-validation auto;"
            # in named.conf.
            #
            # This key (19036) is to be phased out starting in 2017. It will
            # remain in the root zone for some time after its successor key
            # has been added. It will remain this file until it is removed from
            # the root zone.
            . initial-key 257 3 8 "AwEAAagAIKlVZrpC6Ia7gEzahOR+9W29euxhJhVVLOyQbSEW0O8gcCjF
                    FVQUTf6v58fLjwBd0YI0EzrAcQqBGCzh/RStIoO8g0NfnfL2MTJRkxoX
                    bfDaUeVPQuYEhg37NZWAJQ9VnMVDxP/VHL496M/QZxkjf5/Efucp2gaD
                    X6RS6CXpoY68LsvPVjR0ZSwzz1apAzvN9dlzEheX7ICJBBtuA6G3LQpz
                    W5hOA2hzCTMjJPJ8LbqF6dsV6DoBQzgul0sGIcGOYl7OyQdXfZ57relS
                    Qageu+ipAdTTJ25AsRTAoub8ONGcLmqrAmRLKBP1dfwhYB4N7knNnulq
                    QxA+Uk1ihz0=";

            # This key (20326) is to be published in the root zone in 2017.
            # Servers which were already using the old key (19036) should
            # roll seamlessly to this new one via RFC 5011 rollover. Servers
            # being set up for the first time can use the contents of this
            # file as initializing keys; thereafter, the keys in the
            # managed key database will be trusted and maintained
            # automatically.
            . initial-key 257 3 8 "AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3
                    +/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kv
                    ArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF
                    0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+e
                    oZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfd
                    RUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwN
                    R1AkUTV74bU=";
    };

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rootkey-config
  namespace: bind9
data:
  named.root.key: |
    managed-keys {
          # ROOT KEYS: See https://data.iana.org/root-anchors/root-anchors.xml
          # for current trust anchor information.
          #
          # These keys are activated by setting "dnssec-validation auto;"
          # in named.conf.
          #
          # This key (19036) is to be phased out starting in 2017. It will
          # remain in the root zone for some time after its successor key
          # has been added. It will remain this file until it is removed from
          # the root zone.
          . initial-key 257 3 8 "AwEAAagAIKlVZrpC6Ia7gEzahOR+9W29euxhJhVVLOyQbSEW0O8gcCjF
                  FVQUTf6v58fLjwBd0YI0EzrAcQqBGCzh/RStIoO8g0NfnfL2MTJRkxoX
                  bfDaUeVPQuYEhg37NZWAJQ9VnMVDxP/VHL496M/QZxkjf5/Efucp2gaD
                  X6RS6CXpoY68LsvPVjR0ZSwzz1apAzvN9dlzEheX7ICJBBtuA6G3LQpz
                  W5hOA2hzCTMjJPJ8LbqF6dsV6DoBQzgul0sGIcGOYl7OyQdXfZ57relS
                  Qageu+ipAdTTJ25AsRTAoub8ONGcLmqrAmRLKBP1dfwhYB4N7knNnulq
                  QxA+Uk1ihz0=";

          # This key (20326) is to be published in the root zone in 2017.
          # Servers which were already using the old key should roll to the
          # new # one seamlessly.  Servers being set up for the first time
          # can use either of the keys in this file to verify the root keys
          # for the first time; thereafter the keys in the zone will be
          # trusted and maintained automatically.
          . initial-key 257 3 8 "AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3
                  +/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kv
                  ArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF
                  0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+e
                  oZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfd
                  RUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwN
                  R1AkUTV74bU=";
    };

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rfczone-config
  namespace: bind9
data:
  named.rfc1912.zones: |
    // named.rfc1912.zones:
    //
    // Provided by Red Hat caching-nameserver package 
    //
    // ISC BIND named zone configuration for zones recommended by
    // RFC 1912 section 4.1 : localhost TLDs and address zones
    // and http://www.ietf.org/internet-drafts/draft-ietf-dnsop-default-local-zones-02.txt
    // (c)2007 R W Franks
    // 
    // See /usr/share/doc/bind*/sample/ for example named configuration files.
    //

    zone "localhost.localdomain" IN {
      type master;
      file "named.localhost";
      allow-update { none; };
    };

    zone "localhost" IN {
      type master;
      file "named.localhost";
      allow-update { none; };
    };

    zone "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa" IN {
      type master;
      file "named.loopback";
      allow-update { none; };
    };

    zone "1.0.0.127.in-addr.arpa" IN {
      type master;
      file "named.loopback";
      allow-update { none; };
    };

    zone "0.in-addr.arpa" IN {
      type master;
      file "named.empty";
      allow-update { none; };
    };
